---
- name: Pull docker image of teleconsulting platform user portal
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/gaparul/teleconsultingplatform-userportal:latest
      
    - name: running container
      shell: docker run -it -p 3001:3001 -d gaparul/teleconsultingplatform-userportal:latest